### ISSUE TITLE
fix multiline not updating

### ISSUE THREAD

**Issue by juanrein** [TIMath23/TIM#115]
- tuo monirivien meneminen päällä jos lisää matikkaeditorossa toisen kaavan on
  hyvä idea.  Sain kuitenkin preview:n sekaisin lisäämällä ja poistamlla uuden
  kaavan (ruksi näytti yksirivistä, mutta previewssa oli edelleen monirivinen
  jonka toinen kaava oli 2 ja toinen 4 ks *).

*) Tapa sotkea previe:

1) Aloita yksirivisellä kaavalla jossa on 2
2) Paina +
3) tulee monirivinen, lisää kaavaksi 4
4) poista nykyinen rivi (editoriin jää 2 ja 4 päälekkäin)

**Comment by janmatla** [comment]
Preview is updated by 'updateFormulaToEditor' method. Removing a field doesn't trigger it so added a call for it at the end of 'removeField' method.
