### ISSUE TITLE
Preview selection not working in some situations

### ISSUE THREAD

**Issue by juanrein** [TIMath23/TIM#162]
- ekan tehtävän preview:ssa voi klikata monirivisen kaavan A= pii r2 kohtaa ja
  pääsen matikkaeditoriin.  Mutta muista kaavoista en pääse?

**Comment by janmatla** [comment]
Problem appears to happen with formulas with begin-end notation

**Comment by juanrein** [comment]
Malformed syntax doesn't get unambiguously evaluated by katex so direct string comparison doesn't work in some situations

**Comment by juanrein** [comment]
Maybe \cases etc. should make the formula multiline

**Comment by juanrein** [comment]
could make formula-utils more resistant to erronous input

**Comment by juanrein** [comment]
skip non-matching or trim all white-space and try match again

**Comment by janmatla** [comment]
Line breaks in strings are replaced with spaces before comparison
