### ISSUE TITLE
Add more variety to button configuration

### ISSUE THREAD

**Issue by juanrein** [TIMath23/TIM#168]
- Olisiko tuohon button: -syntaksiin vaikka joku

[ "\\( \\mu \\)", "\\mu", "mu", "symbol"]

jos viimeinen on

 "symbol", menee symbolidiviin
 "math"  , menee TIM-editorin diviin
 "quick" , menee Kaava-painikkeen riville (saa keksiä muunkin nimen)
 "math,symbol", menee sekä symbolidiviin että TIM-editorin diviin
 jne..  (vaikka muissa kombinaatioissa ei ole mieltä)

ja sitten noita voisi myös lyhentää

 "s"
 "m"
 "q"
 "m,s"

**Comment by JaakkoP1998** [comment]
En tiedä kannattaako "math" attribuuttia lyhentää, se saattaa rikkoa monta olemassa olevaa TIM-dokumenttia.

**Comment by Philetairos** [comment]
kombinaatioita ei toteutettu mutta se ei ole välttämätöntä
