### ISSUE TITLE
Shorten the symbolbuttons syntax

### ISSUE THREAD

**Issue by JaakkoP1998** [TIMath23/TIM#172]
For example symbolbutton:
[ "\\( \\mu \\)", "\\mu", "mu", "symbol"]
to
[ "\\( \\mu \\)", "\\mu", "mu", "s"]
where
"s" means its symbolbutton and "q" means its default symbolbutton.
Maybe do not shorten "math" since that might break multiple existing TIM-documents.
Also add hybrid attribute "math,s", that means it goes to symbolbuttons and regular templatebuttons.

**Comment by juanrein** [comment]
https://github.com/TIMath23/TIM/issues/168 Tää on kai sama
