### ISSUE TITLE
Add shorter form to buttons

### ISSUE THREAD

**Issue by juanrein** [TIMath23/TIM#193]
- Kun katsoo tuota määrittelyn gitlab-tiedostoa, tulee mieleen että kuink
  usein toimisi että kun kirjoittaa

      text: "\\[ f(\\square) \\]",
    
  niin sitten olisi seuraava algoritmi:

    1. jos `data` puuttuu, niin se tehdään tekstistä poistamalla '\\[' ja vastaava lopetus
       ja `\\square`.
    2. jos `expl` puuttuu, niin se tehdää `datasta` (joka valmiista tai kohdassa 1 tehdystä)
       poistamalla `⁞`-merkki.

  Silloin vaikuttauisi että useimiten riittäisi kirjoittaa vain itse `text`.
  Ja sama tietty siinä YAMLin yhden rivin muodossa (miten viiminen paramteri saadaan
  helpoiten sanottua jos muut puuttuvat).  Erikoistapauksissa sitten kirjoitetaan
  enemmän.

ehkä voisi vaihtaa ensimmäisen vastaantulevan \\squaren kursoriksi:
[ "\\[ \\frac{\\square}{\\square} \\]", "s" ]
-> "\\frac{\\square}{\\square}"
-> "\\frac{⁞}{}"

[ "\\[ \\frac{\\square}{\\square} \\]", "\\frac{⁞}{}", "\\frac{ }{}", "q" ]

[ "\\[ \\frac{\\square}{\\square} \\]", "\\frac{⁞}{}", "q" ]

[ "\\[ \\frac{\\square}{\\square} \\]", "q" ]

[ "\\( T \\)", "\\mathrm{⁞}", "\\mathrm{ }", "s" ]

[ "\\( sin \\)", "\\sin","\\sin", "s"]

[ "\\( \\Phi \\)", "\\Phi", "\\Phi", "s"]

[ "$$", "$$⁞$$", "$$ $$",  "t" ]

[ "\\( \\pm \\)", "\\pm", "\\pm", "q"]

**Comment by Philetairos** [comment]
ii on käytännössä toteutettu ⁞-merkin poistamista lukuun ottamatta

**Comment by Philetairos** [comment]
https://github.com/TIMath23/TIM/commit/db8f39e683dccc59403cc0674c1824123c6c4917
