### ISSUE TITLE
put your name in files

### ISSUE THREAD

**Issue by juanrein** [TIMath23/TIM#204]
https://tim.jyu.fi/view/tim/TIMin-kehitys/sovellusprojektit#authoring

- [x]  Juha
- [x] Jaakko
- [x] Janne
- [x] Daniel

**Comment by JaakkoP1998** [comment]
Laitetaanko kaikkiin mitä ollaan muutettu, vai vaan mitä ollaan luotu?

**Comment by juanrein** [comment]
Tossa linkitetyssä ohjeessa on vastaus

**Comment by Philetairos** [comment]
Mitä tiedostoja me ollaan "muokattu merkittävästi"? varmaan ainakin csPlugin.ts jne.

**Comment by juanrein** [comment]
Voiaan ehkä kysyä perjantaina koodikatselmoinnissa merkittävän merkitystä
