### ISSUE TITLE
Fix cancel by esc causing expression has changes

### ISSUE THREAD

**Issue by juanrein** [TIMath23/TIM#227]
ExpressionChangedAfterItHasBeenChecked error happens when writing in latex field and pressing esc key

**Comment by Philetairos** [comment]
https://stackoverflow.com/questions/43375532/expressionchangedafterithasbeencheckederror-explained

**Comment by Philetairos** [comment]
https://github.com/TIMath23/TIM/commit/f14737da5aa2af9ab2f78e73c2d28898166d9199
