### ISSUE TITLE
undo/redo in visual editor

### ISSUE THREAD

**Issue by juanrein** [TIMath23/TIM#60]
https://www.geeksforgeeks.org/implement-undo-and-redo-features-of-a-text-editor/

**Comment by Philetairos** [comment]
Pikanäppäimet ctrl z ja ctrl y jo tekevät nämä

**Comment by Philetairos** [comment]
https://github.com/digabi/rich-text-editor/blob/master/src/math-editor.js
Abitti undo & redo

**Comment by Philetairos** [comment]
https://stackoverflow.com/questions/14747537/implementin-undo-redo-in-math-editor
